package swing;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

import entities.DataBase.DAO;
import entities.records.SessaoAtual;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;

/**
 *
 * @author Dell
 */
public class MainFrameFunc extends java.awt.Frame {

    /**
     * Creates new form MainFrame
     */
    public MainFrameFunc () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(880, 432));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel2.setText("Lista de funcionários");
        jPanel1.add(jLabel2);

        add(jPanel1, java.awt.BorderLayout.NORTH);


        jPanel2.setPreferredSize(new java.awt.Dimension(250, 300));

        jLabel1.setText("Suas informações:");
        jPanel2.add(jLabel1);

        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel3);

        jLabel4.setText("jLabel3");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel4);

        jLabel5.setText("jLabel3");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel5);

        jLabel6.setText("jLabel3");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel6);

        jLabel7.setText("jLabel3");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel7);

        jPanel3.add(jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Nome", "Turno", "Setor", "Função"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setBackground(new java.awt.Color(173, 216, 240));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setPreferredSize(new java.awt.Dimension(205, 350));
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionBackground(new java.awt.Color(173, 216, 240));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Encerrar sessão");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.setBackground(new Color(255,105,97));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }

        });

        jPanel2.add(jButton5);
        jPanel3.add(jScrollPane1);

        add(jPanel3, java.awt.BorderLayout.CENTER);
        atualizarTabela();
        infopessoais();
        pack();
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12));
        jPanel1.setBackground(new java.awt.Color(173, 216, 240));
        jPanel2.setBackground(new java.awt.Color(173, 216, 240));
        jPanel3.setBackground(new java.awt.Color(173, 216, 240));
    }// </editor-fold>

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        new telalogin().setVisible(true);
        dispose();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameFunc().setVisible(true);
            }
        });
    }
    public static void infopessoais(){
        DAO dataBase = new DAO();
        try{
            SessaoAtual sessao=DAO.getSessao();
            System.out.println(sessao);
            String login='"'+sessao.loginAtual()+'"';
            System.out.println();
            Statement st = dataBase.con.createStatement();
            String sql = "Select * from funcionarios WHERE Login="+ login;
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String nome = String.valueOf(rs.getString("Nome"));
                String salario = String.valueOf(rs.getDouble("Salario"));
                String turno = String.valueOf(rs.getString("Turno"));
                String setor = String.valueOf(rs.getString("NomeSetor"));
                String funcao = String.valueOf(rs.getString("Funcao"));

                jLabel3.setText("Nome: "+nome);
                jLabel4.setText("Salário: "+salario);
                jLabel5.setText("Turno: "+turno);
                jLabel6.setText("Setor: "+setor);
                jLabel7.setText("Função: "+funcao);

            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public static void atualizarTabela(){
        DAO dataBase = new DAO();
        try{
            SessaoAtual sessao=DAO.getSessao();
            System.out.println(sessao);
            String login='"'+sessao.loginAtual()+'"';
            System.out.println();
            Statement st = dataBase.con.createStatement();
            String sql = "Select * from funcionarios WHERE Login <> "+ login;
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            tableModel.setRowCount(0);
            while(rs.next()){
                String nome = String.valueOf(rs.getString("Nome"));
                String turno = String.valueOf(rs.getString("Turno"));
                String setor = String.valueOf(rs.getString("NomeSetor"));
                String funcao = String.valueOf(rs.getString("Funcao"));

                String tbData[] = {nome,turno,setor,funcao};
                tableModel.addRow(tbData);

            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jButton5;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration
}

